### ISSUE TITLE
Could not install package 'DotNetRuleEngine 2.0.1'

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [ayayalar/DotNetRuleEngine#1]
i am trying to install this to a class library and i am getting below error from VS 13/Nuget 

Severity	Code	Description	Project	File	Line
Error		Could not install package 'DotNetRuleEngine 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by ayayalar** [comment]
Hi Rajesh,
DotNetRuleEngine targets .net version 4.6.1. You can either upgrade your project to 4.6.1 or download the source code and target 4.5

**Comment by rajeshmuraleedharan** [comment]
Sure i can upgrade to 4.6.1. It would be nice if you can provide 4 or 4.5 targets.

**Comment by ayayalar** [comment]
Sure I can include them in the next release of the nuget package.
Thank you




    _____________________________
