### ISSUE TITLE
How to make this more generic?

### ISSUE THREAD

**Issue by deostroll** [ayayalar/DotNetRuleEngine#2]
```
var ruleResults = RuleEngine<Order>.GetInstance(order)
    .ApplyRules(new QualifiesForFreeShipping())
    .Execute()
```

How to make `Order` itself generic, meaning load that type from another assembly, and be able to execute code in a pattern similar to above?

**Comment by ayayalar** [comment]
One option would be you can create generic rule(s) based on some abstract type.  Example:


```
public class MyRule<T> : Rule<T> where T : MyClass, new()
{
	public override IRuleResult Invoke()
	{
		return null;
	}
}

public abstract class MyClass
{
	public MyClass()
	{		
	}
}
```


And then init rule engine with the abstract type


`RuleEngine<MyClass>.GetInstance(...)
`

**Comment by deostroll** [comment]
So the lib does not support a scenario where the model and rules are
dynamic - created on-the-fly, at runtime...?

**Comment by ayayalar** [comment]
I don't know exactly what you are trying to accomplish. But you would get the most use out of it when you create a RuleEngine per type. A rule engine represents set of rules for a type (your domain object). However you can create rule engine for the object or dynamic types. In my opinion it defeats the purpose but it is totally possible. Then in each rule created you would need to determine the type to cast/convert.





On Tue, Mar 15, 2016 at 8:11 PM -0700, "arun.jayapal" <notifications@github.com> wrote:










So the lib does not support a scenario where the model and rules are

dynamic - created on-the-fly, at runtime...?
