### ISSUE TITLE
CPU utilization high

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [ayayalar/DotNetRuleEngine#4]
Hi,
I am using async parallel rules. I have around 30 rules and  implemented in asp.net Web api. This is for a trading app, rules used to  check trade date and maturity dates, compliance rules. 

When clients sends request  (around 100 trades) these rules are evaluated. I am using parallel foreach for trades collection. Request completes in around 3 to 5 seconds. But CPU utilization goes to around 60%, if there are multiple requests then CPU utilization reaches 100% for few seconds. This causing issues on the server. Our server has 4 cores. 

I removed trades parallel foreach, that reduced CPU utilization little bit. Issues still there when there are multiple requests. Have you noticed this issue? Is there configuration available to specify parallel rules execute thread count at a time?

**Comment by ayayalar** [comment]
Hi Raj,

Thanks for reporting the problem. I have a test runs about 1,000,000 rules. Let me re-run and see whats going on. Which version of DotNetRuleEngine are you using?

**Comment by ayayalar** [comment]
I just ran the test again, it reaches up to 70% CPU utilization running 1,000,000 rules.  This is the rule I am running:

```
class PerfRule : RuleAsync<Foo>
{
	public override Task InitializeAsync()
	{		
		IsParallel = true;
		return Task.FromResult<object>(null);
	}
	public async override Task<IRuleResult> InvokeAsync()
	{
		await Task.Delay(100);
		Math.Sqrt(new Random(Guid.NewGuid().GetHashCode()).Next());
		return await Task.FromResult<IRuleResult>(null);
	}
}
```

**Comment by ayayalar** [comment]
One more test calculating a random large prime number in the rule which is a very expensive operation. With 100,000 rules the CPU utilization remains under 50%.

**Comment by ayayalar** [comment]
I made a few changes how parallel rules executed. Can you grab the changes from the v3.0.3 branch and give it a try?

**Comment by rajeshmuraleedharan** [comment]
i upgraded the package from 2.0.5 to 3.0.3. But still i can see cpu utilization reached above 95% for few seconds when there are four or five requests at a time.

**Comment by ayayalar** [comment]
Are you sure RuleEngine is causing the spike? After my changes, calculating a prime number (which is very high cpu intensive process) the cpu utilization stays at 50% at most with 1,000,000 rules. If you like I can send you the rule you can test it on your end as well.

**Comment by ayayalar** [comment]
Here is the rule if you would like to give it a try

```csharp
void Main()
{
    IList<IGeneralRule<Foo>> rules = new List<IGeneralRule<Foo>>();

    for (int i = 0; i < 1000000; i++)
    {
        rules.Add(new CalculatePrimeNumber());
    }

    var rr = RuleEngine<Foo>.GetInstance(new Foo());
    rr.AddRules(rules.ToArray());
    var result = await rr.ExecuteAsync();
}

class CalculatePrimeNumber : DotNetRuleEngine.Core.RuleAsync<Foo>
{
	public override Task InitializeAsync()
	{		
		IsParallel = true;
		return Task.FromResult<object>(null);
	}
	public async override Task<IRuleResult> InvokeAsync()
	{		
		FindPrimeNumber((int)Math.Sqrt(new Random(Guid.NewGuid().GetHashCode()).Next()));
		return await Task.FromResult<IRuleResult>(null);
	}

	long FindPrimeNumber(int n)
	{
		int count = 0;
		long a = 2;
		while (count < n)
		{
			long b = 2;
			int prime = 1;// to check if found a prime
			while (b * b <= a)
			{
				if (a % b == 0)
				{
					prime = 0;
					break;
				}
				b++;
			}
			if (prime > 0)
				count++;
			a++;
		}
		return (--a);
	}
}
```

CPU utilization stays around this percentage below

![image](https://cloud.githubusercontent.com/assets/130195/19395429/6870e5b6-91f2-11e6-9288-98c4a121449c.png)

**Comment by ayayalar** [comment]
Haven't heard back from you. Closing ticket. Feel free to reopen if you like to discuss further.

**Comment by rajeshmuraleedharan** [comment]
Hi,
Sorry for the late reply, I got some other assignment and was busy in that. Last week i was able to figure out the high CPU issue. It was with our legacy code. We have an old Business Rule library which i was referred through DotNetRuleEngine. In that reflection was used in a bad way. Code fixed and no more CPU utilization issues. Now api performance increased to 1.5 seconds from 16 seconds.   Once again Thank you for your quick response to this.

**Comment by ayayalar** [comment]
Raj, great news. Glad you solved the problem. FYI, the DotNetRuleEngine version 3.0.3 I've released yesterday uses PreferFairness for parallel rules by default to ensure/avoid CPU spikes.
