### ISSUE TITLE
Defining rules via data

### ISSUE THREAD

**Issue by hades200082** [ayayalar/DotNetRuleEngine#5]
Hi

I'm really impressed with this project.  I was wondering if there's a way to define rules in a way that could be stored in a database to allow for rules to be configured at runtime?

If this was possible then this library could become very powerful in applications such as product configuration.

**Comment by ayayalar** [comment]
Hi Lee, Thank you. There is definitely more than one way of going about this. Depending on what makes more sense to you. One approach I would take, let the data drive the rules defined at runtime. 

In the example below, I've defined a rule to log my model. However the rule would only execute if the rule constraint evaluates to true. And the data injected via the dependency injection at **runtime** which drives the behavior of the rule.

Would that solve the problem for you?

Example:
```
class LoggingRule : Rule<Model>
{
    ILogger _logger;
    ILogConfiguration _logConfiguration;

    public LoggingRule(ILogger logger, ILogConfiguration logConfiguration)
    {
        _logger = logger;
	_logConfiguration = logConfiguration;
    }

    public override Task Initialize()
    {
        Configuration.Constraint = model => _logConfiguration.EnableLogging;
        return null;
    }

    public override IRuleResult Invoke()
    {
        _logger.log(...);
	return null;
    }
}
```
