### ISSUE TITLE
Adding RuleResult from Initialize method

### ISSUE THREAD

**Issue by ben-jacobs** [ayayalar/DotNetRuleEngine#6]
Loving this library :-)

For certain rules (with expensive external calls etc) I'd like to skip them if the rule was previously run within say the last 10 minutes. This is easy to do by adding a constraint in the rule initialization method.

I would however like to add a rule result that reports the rule was skipped, and the last execution time (so if the rule runs again in say 10 minutes time the rule will be executed).

As the RuleResults collection is private, I don't think I can add a rule result form the Initialize method.

I'd like your advice on whether you think it's preferable to:

Modify the source to make the ruleresults collection public (or add a public method to add a rule result etc.)
Or
Forget about using Configuration.Constraints in the Initialize method, and just do these checks within the rule execution.

The second option is obviously easiest, but it is kind of counter-intuitive and I like the separation of concerns by splitting the configuration and the actual rule processing. I do realise it's kind of odd to have a rule result when the rule hasn't actually run.

Any thoughts?

**Comment by ayayalar** [comment]
Hi Ben,
I’m glad you liking the lib. There are various ways of going about this. And probably depends on how you want to approach it. However this is what I would do.

Add a rule that has two nested rules. One of the nested rules would have a constraint that it would execute the expensive call and returns a rule result that the expensive call was executed. Other nested rule constraint would match the expensive call was already executed (n) minutes ago and returns rule result that the expensive call didn’t not get executed.

This way you would continue maintaining separation of concern by introducing rules that do one thing only.

I hope that helps.

Cheers,
